// THIS FILE IS AUTOMATICALLY GENERATED
#include "range.h"
#include "font_ranges.h"

bool is_zero_width(uint16_t codept) {
    return RANGE(codept, 1425, 1472) || RANGE(codept, 1473, 1475) || RANGE(codept, 1476, 1478) || RANGE(codept, 1479, 1480) || RANGE(codept, 1552, 1563) || RANGE(codept, 1611, 1632) || RANGE(codept, 1750, 1756) || RANGE(codept, 1759, 1769) || RANGE(codept, 1770, 1774) || RANGE(codept, 2230, 2303);
}
