#include "pebble.h"
#include "range.h"
// THIS FILE IS AUTOMATICALLY GENERATED

extern const uint8_t ARABIC_SHAPER_LUT[];
#define ARABIC_SHAPER_LUT_SIZE 462
extern const uint8_t ARABIC_LIGATURE_LUT[];
#define ARABIC_LIGATURE_LUT_SIZE 6
#define ARABIC_SHAPER_RANGE(cp) (RANGE(cp, 1792, 1872) || RANGE(cp, 1920, 2044))
